Javascript application for fuzzing
CodeIntelligenceTesting/ci-fuzz-cli-tutorials pull request #2
Opened 2023-07-28 16:27 UTC by turalsalamov

It is a nodejs javascript demo application with vulnerability for fuzzing. Details of application are described in README.md file.

2023-07-31 13:27 UTC, 0xricksanchez requested changes

2023-07-31 13:27 UTC, 0xricksanchez commented on js_ts/nodejs-js/README.md
> +### Usage of application
```suggestion
## Functionality
```

2023-07-31 13:27 UTC, 0xricksanchez commented on js_ts/nodejs-js/README.md
> +# Nodejs JS demo application
```suggestion
# NodeJS demo application
```

2023-07-31 13:27 UTC, 0xricksanchez commented on js_ts/nodejs-js/README.md
> +It is simple nodejs express TODO application which has several functionalities, such as, adding,
```suggestion
It is simple nodeJS express TODO application, which has several functionalities, such as, adding, 
```

2023-07-31 13:27 UTC, 0xricksanchez commented on js_ts/nodejs-js/README.md
> +deleting, listing TODOs, deleting whole json file and command execution in the server. The application creates
```suggestion
deleting single TODOs, and listing TODOs. Additional functionality includes, deleting the whole TODO list json file and command execution on the server. The application creates 
```

2023-07-31 13:27 UTC, 0xricksanchez commented on js_ts/nodejs-js/README.md
> +todo.json file in the root folder of the application.
```suggestion
a `todo.json` file in the root folder of the application as a database to save all added TODOs.
```

2023-07-31 13:27 UTC, 0xricksanchez commented on js_ts/nodejs-js/README.md
> +`/api/server?command=<command>`
```suggestion
Available endpoints: 
    
```
/api/add?todo=<todo>&deadline=<deadline>
/api/delete?id=<id>
/api/list
/api/deleteList
/api/server?command=<command>
```

```

2023-07-31 13:27 UTC, 0xricksanchez commented on js_ts/nodejs-js/package.json
> +  "description": "Nodejs Javascript tutorial example",
```suggestion
  "description": "NodeJS tutorial example",
```

2023-07-31 13:27 UTC, 0xricksanchez commented on js_ts/nodejs-js/package.json
> +  "name": "nodejs",
```suggestion
  "name": "TODO list server",
```

2023-07-31 13:27 UTC, 0xricksanchez commented on js_ts/nodejs-js/utils.js
> +module.exports = {TODO, commandExecution, addEntry, deleteEntry, deleteFile, listFile}
```suggestion
const fs = require('fs');
const child_process = require('child_process')

class TODO {
    constructor(id, todo, deadline) {
        this.id = id;
        this.todo = todo;
        this.deadline = deadline;
    }
}

const filePath = './todo.json';

function fileIsPresent() {
    return fs.existsSync(filePath);
}

function writeToFile(data) {
    try {
        fs.writeFileSync(filePath, JSON.stringify(data));
    } catch (e) {
        console.error('Error while writing to file:', e);
    }
}

function readFromFile() {
    try {
        return JSON.parse(fs.readFileSync(filePath).toString());
    } catch (e) {
        console.error('Error while reading from file:', e);
    }
    return null;
}

function createAndWrite(dataToWrite) {
    dataToWrite.id = 1;
    writeToFile([dataToWrite]);
}

function deleteEntry(id) {
    if (fileIsPresent()) {
        let content = readFromFile();
        if (content) {
            let index = content.findIndex(element => element.id === id);
            if (index >= 0) {
                content.splice(index, 1);
                writeToFile(content);
                return true;
            }
        }
    }
    return false;
}

function addEntry(dataToWrite) {
    if (fileIsPresent()) {
        let content = readFromFile();
        if (content) {
            let lastId = content[content.length - 1].id;
            dataToWrite.id = lastId + 1;
            content.push(dataToWrite);
            writeToFile(content);
            return true;
        }
    } else {
        createAndWrite(dataToWrite);
        return true;
    }
    return false;
}

function deleteFile() {
    try {
        if (fileIsPresent()) {
            fs.unlinkSync(filePath);
            return true;
        }
    } catch (e) {
        console.error('Error while deleting file:', e);
    }
    return false;
}

function listFile() {
    if (fileIsPresent()) {
        const content = readFromFile();
        if (content) {
            return content.map(element => `Id: ${element.id}\tTODO: ${element.todo}\tDeadline: ${element.deadline}`).join('\n');
        }
    }
    return null;
}

function commandExecution(command, fn) {
    child_process.exec(command, (err, stdout, stderr) => {
        fn(stdout)
    });
}

module.exports = { TODO, addEntry, deleteEntry, deleteFile, listFile, commandExecution }

```

That should be more aligned with modern JavaScript.

2023-07-31 13:27 UTC, 0xricksanchez commented on js_ts/nodejs-ts/.gitignore
> +package-lock.json
JS comments also apply to the TS side. I'll leave adding these to the TS side to you @turalsalamov

2023-08-07 13:46 UTC, 0roman commented
Add an entry in the [README](https://github.com/CodeIntelligenceTesting/ci-fuzz-cli-tutorials/blob/main/README.md) for the new tutorials.

2023-08-23 12:47 UTC, merged